name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          python-version: "3.11"
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y openjdk=17
          if [ -f environment.yml ]; then
            conda env update -n test-env -f environment.yml
          else
            pip install -r requirements.txt
          fi

      - name: Run tests
        shell: bash -l {0}
        run: pytest -q
